# Generated by Django 5.2.3 on 2025-11-14 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('management', 'Management'), ('production', 'Production'), ('research', 'Research & Development'), ('quality', 'Quality Control'), ('sales', 'Sales & Marketing'), ('customer', 'Customer Support'), ('logistics', 'Logistics'), ('admin', 'Administrative Staff')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.role'),
        ),
    ]
