# Generated by Django 5.2.3 on 2025-11-15 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_alter_message_role'),
        ('product', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('ai_model', models.CharField(default='openai/gpt-oss-20b:groq', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=300)),
                ('use_history', models.BooleanField(default=True)),
                ('use_role_context', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_experiment', models.ForeignKey(blank=True, help_text="If selected, AI will use this experiment's description and lab notes as context.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_users', to='research.experiment')),
                ('context_products', models.ManyToManyField(blank=True, help_text='AI will reference these products during responses.', related_name='ai_context_users', to='product.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
