# Generated by Django 5.2.3 on 2025-11-14 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'permissions': [('can_create_notification', 'Can create notification')]},
        ),
    ]
